extract:
  - HOSTNAME
  - os
  - IP
  - distro

output:
  formats:
    json:
      path: test/output.json
      stdout: true
    yaml:
      path: test/output.yaml
      stdout: true
    env:
      path: test/.env
      stdout: true
